server:
  max-http-header-size: 4048576
  tomcat:
    #max-http-post-size: 100MB  #请求参数长度
    max-http-form-post-size: 100MB  #请求参数长度

# 数据源, alibaba druid连接池
spring:
  # SB 2.0x
  servlet :
    multipart:
      enabled: true
      max-file-size: 100MB # 单个文件上传大小
      max-request-size: 1000MB # 总上传大小
      